import { Loading, Note, Page, Spacer, Text } from '@geist-ui/core'
import type { NextPage } from 'next'
import Head from 'next/head'
import CodeSnippts from '../components/CodeSnippts'
import config from '../config'
import useSnippts from '../hooks/useSnippts'

const Home: NextPage = () => {
  const snippts = useSnippts()
  const currentSnippts = snippts.all(0, config.site.entriesPerPage)

  return (
    <Page dotBackdrop>
      <Head>
        <title>Modelo: Instantly record your codes.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Text h1>Modelo.</Text>
      <Text h3>Instantly record your codes.</Text>

      <Spacer h={2} />
      <Text h2>Recent snippts</Text>

      <Spacer h={2} />

      {currentSnippts.isError && (
        <Note type="error" label="ERROR">
          Failed to load snippts. Please try again.
        </Note>
      )}

      {currentSnippts.isLoading || currentSnippts.isError ? (
        <>{currentSnippts.isLoading && <Loading />}</>
      ) : (
        <CodeSnippts snippts={currentSnippts.data?.data || []} />
      )}
    </Page>
  )
}

export default Home
