import type { NextPage } from 'next'
import Head from 'next/head'
import { Grid, Loading, Note, Page, Spacer, Text } from '@geist-ui/core'
import useTemplates from '../hooks/useTemplates'
import CodeTemplate from '../components/CodeTemplate'

const Home: NextPage = () => {
  const templates = useTemplates()
  const allTemplates = templates.all()

  return (
    <Page dotBackdrop>
      <Head>
        <title>Modelo: Instantly record your codes.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Text h1>Modelo.</Text>
      <Text h3>Instantly record your codes.</Text>

      <Spacer h={2} />

      {allTemplates.isError && (
        <Note type="error" label="ERROR">
          Failed to load templates. Please try again.
        </Note>
      )}

      {allTemplates.isLoading || allTemplates.isError ? (
        <>{allTemplates.isLoading && <Loading />}</>
      ) : (
        <Grid.Container gap={3}>
          {allTemplates.data?.data.map((template, index) => (
            <Grid xs={24} md={12} lg={8} key={index}>
              <CodeTemplate data={template} />
            </Grid>
          ))}
        </Grid.Container>
      )}
    </Page>
  )
}

export default Home
